CREATE DATABASE bankdb;
USE bankdb;

CREATE TABLE users (
	fName VARCHAR(20) NOT NULL,
    lName VARCHAR(20) NOT NULL,
    SSN INT NOT NULL PRIMARY KEY,
    Address VARCHAR(20) NOT NULL,
    phoneNum VARCHAR(20) NOT NULL,
    pw VARCHAR(20) NOT NULL
);
SELECT * FROM TABLE;